version: "3.8"

services:
  demo:
    container_name: "demo_demo"
#    ports:
#      - "80:80"
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m demo
    restart: always
    volumes:
      - "./src:/opt/src:ro"
      - "./demo:/opt/demo:ro"
      - "./pages:/opt/pages:ro"
      - "./templates:/opt/templates:ro"
    environment:
      SESSION_STORAGE_URL: redis://demo:6379/0
    env_file:
      - ".env"
    depends_on:
      - db
      - redis

  migrations:
    container_name: "demo_migrations"
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m migrations
    volumes:
      - ".:/opt:rw"
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    container_name: "demo_db"
    image: postgres:16-alpine3.19
    hostname: "demo"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin

  redis:
    container_name: "demo_redis"
    hostname: "demo"
    restart: always
    image: redis:7.2.2-alpine3.18

  server:
    container_name: "demo-nginx"
    image: nginx:1.25.3-alpine3.18
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./certs:/etc/nginx/certs:ro"
      - "./log:/var/log/nginx:rw"
      - "./static:/opt/static:ro"
      - "./templates:/opt/templates:ro"
    depends_on:
      - demo
